// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub const S = struct {
    v: i64,
    hits: i64,
};

pub fn tickStep(ctx: *rt.Ctx, s: S, delta: i64) S {
    _ = ctx;
    return S{ .v = (s.v + delta), .hits = (s.hits + 1) };
}

/// Commit-boundary copy: world state leaves tick memory by
/// value (escape-checked slice-free in v1).
pub fn promote(v: S) S {
    return v;
}
