// generated by beagle (odin backend) — do not edit
package ecs


Position :: struct {
    x: f32,
    y: f32,
    z: f32,
    active: bool,
}

Velocity :: struct {
    dx: f32,
    dy: f32,
    dz: f32,
    active: bool,
}
